openapi: 3.0.3
info:
  title: Customer Orders API
  description: API to manage customers and their orders of meals
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  '/customers/{customerId}/orders':
    get:
      tags:
        - Order
      summary: Get all orders for a specific customer
      operationId: getCustomerOrders
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: ID of the customer
      responses:
        '200':
          description: List of orders for a customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Order
      summary: Create a new order for a customer
      operationId: createCustomerOrder
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: ID of the customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      tags:
        - Order
      summary: Update an existing order for a customer
      operationId: updateCustomerOrder
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: ID of the customer
        - name: orderId
          in: query
          required: true
          schema:
            type: string
          description: ID of the order to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        reference:
          type: string
          description: Unique order reference, not a primary key
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: '#/components/schemas/Meal'
              quantity:
                type: integer
                description: Quantity of the meal ordered
        orderDatetime:
          type: string
          format: date-time
          description: Date and time when the order was made, generated by the server
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        available:
          type: boolean
